const gdata = [
  {
    id: 1,
    src: "./images/im.webp",
    name: "iron man",
    category: "Robert Downey Jr.",
    gen: "male",
  },
  {
    id: 2,
    src: "./images/ca.webp",
    name: "captain america",
    category: "chris evans",
    gen: "male",
  },
  {
    id: 3,
    src: "./images/thor.webp",
    name: "Thor",
    category: "Chris Hemsworth",
    gen: "male",
  },
  {
    id: 4,
    src: "./images/bw.webp",
    name: "black widow",
    category: "Scarlett Johansson",
    gen: "female",
  },
  {
    id: 5,
    src: "./images/sw.webp",
    name: "Scarlet Witch",
    category: "Elizabeth Olsen",
    gen: "female",
  },
  {
    id: 6,
    src: "./images/drs.webp",
    name: "Doctor strange",
    category: "Benedict Cumberbatch",
    gen: "male",
  },
  {
    id: 7,
    src: "./images/bp.webp",
    name: "black panther",
    category: "Chadwick Boseman",
    gen: "male",
  },
  {
    id: 8,
    src: "./images/sm.webp",
    name: "Spider-Man",
    category: "Tom Holland",
    gen: "male",
  },
  {
    id: 9,
    src: "./images/rhode.webp",
    name: "War Machine",
    category: "Don Cheadle",
    gen: "male",
  },
  {
    id: 10,
    src: "./images/hulk.webp",
    name: "Hulk",
    category: "Mark Ruffalo",
    gen: "male",
  },
  {
    id: 11,
    src: "./images/sl.webp",
    name: "star lord",
    category: "Chris Pratt",
    gen: "male",
  },
  {
    id: 12,
    src: "./images/drax.webp",
    name: "drax",
    category: "Dave Bautista",
    gen: "male",
  },
  {
    id: 13,
    src: "./images/mantis.webp",
    name: "mantis",
    category: "Pom Klementieff",
    gen: "female",
  },
  {
    id: 14,
    src: "./images/rg.webp",
    name: "Rocket and Groot",
    category: "Bradley Cooper | Vin Diesel",
    gen: "male",
  },
  {
    id: 15,
    src: "./images/tws.webp",
    name: "The winter soldier",
    category: "Sebastian Stan",
    gen: "male",
  },
  {
    id: 16,
    src: "./images/wong.webp",
    name: "wong",
    category: "Benedict Wong",
    gen: "male",
  },
  {
    id: 17,
    src: "./images/vision.webp",
    name: "vision",
    category: "Paul Bettany",
    gen: "male",
  },
  {
    id: 18,
    src: "./images/fal.webp",
    name: "flacon",
    category: "Anthony Mackie",
    gen: "male",
  },
  {
    id: 19,
    src: "./images/ok.webp",
    name: "okoye",
    category: "Danai gurira",
    gen: "female",
  },
  {
    id: 20,
    src: "./images/nebula.webp",
    name: "nebula",
    category: "Karen Gillan",
    gen: "female",
  },
];

export default gdata;
